### ISSUE TITLE
UnicodeEncodeError in one particular case

### ISSUE THREAD

**Issue by BlitzKraft** [heywoodlh/urlscan-py#8]
Full traceback: 

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/email/message.py", line 357, in set_charset
    cte(self)
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/email/message.py", line 365, in set_charset
    payload = payload.encode('ascii', 'surrogateescape')
UnicodeEncodeError: 'ascii' codec can't encode character '\ufeff' in position 0: ordinal not in range(128)                                                                                                          

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bk/.local/bin/urlscan", line 4, in <module>
    __import__('pkg_resources').run_script('urlscan==0.9.3', 'urlscan')
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/mnt/storage/.local/lib64/python3.5/site-packages/urlscan-0.9.3-py3.5.egg/EGG-INFO/scripts/urlscan", line 201, in <module>                                                                                  
    main()
  File "/mnt/storage/.local/lib64/python3.5/site-packages/urlscan-0.9.3-py3.5.egg/EGG-INFO/scripts/urlscan", line 184, in main                                                                                      
    msg = process_input(args.message)
  File "/mnt/storage/.local/lib64/python3.5/site-packages/urlscan-0.9.3-py3.5.egg/EGG-INFO/scripts/urlscan", line 136, in process_input                                                                             
    _msg_set_charset(mesg, enc)
  File "/mnt/storage/.local/lib64/python3.5/site-packages/urlscan-0.9.3-py3.5.egg/EGG-INFO/scripts/urlscan", line 165, in _msg_set_charset                                                                          
    mesg.set_charset(encoding)
  File "/usr/lib64/python3.5/email/message.py", line 367, in set_charset
    payload = payload.encode(charset.output_charset)
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufeff' in position 0: ordinal not in range(256)     
Press any key to continue...
```

`head` of the email message:

```
>    ﻿
> 
>                                     [1]logo
> 
>                           
>                          Hi [name redacted],
>                           
> 
>    Solve today's set of skill tests to benchmark your C++ skills against over
```

The `\uffef` (zero width, no break space) is in the above paste. In the first "empty" looking line.

**Comment by BlitzKraft** [comment]
I forgot to add that the above error occurred when I am using urlscan with mutt (defaults, no extra flags, no  shortening). 

While looking further into this error, I am starting to think this might not be an issue with urlscan - at least not fully. I looked at the full email headers, the charset declared in this email is iso-8859-1 but the `\uFFEF` is not present(?) in that charset. It seems to be used in utf-8-sig and utf-16. 

This might be the cause of the error.

**Comment by heywoodlh** [comment]
When does this error occur? Is it when you're sending an email in Mutt? Can you give me more details on how you're using urlscan-py with Mutt?

Thanks for filing an issue, glad you're finding use in `urlscan-py`! :)

**Comment by BlitzKraft** [comment]
This occurs when piping a message contents to urlscan - this is the line in my muttrc:

```
macro index,pager \cb "<pipe-message>urlscan<enter>" "Call urlscan to extract URLS"
```

`index` and  `pager` are the views/states of the mutt display. `\cb` is the keybinding - Ctrl-b; pipe-message is a mutt command equivalent to piping the text to the given command. The final string is just help text. 

I just tried piping the lines of text directly to urlscan. It was able to run with no issues. Gonna try and find a minimal reproducer.

**Comment by BlitzKraft** [comment]
I can't seem to construct a minimal reproducer. So far, I copied the text to a file and ran urlscan on the file - directly, piped to and through vim. All of them work fine. All of them have the the `\uffef` character. `urlscan` does not reproduce the issue.

I stripped my mutt config in case my rc had the bug. Nope. Still same bug. So, I am pretty sure this bug has something to do with mutt - its `<pipe-message>` feature, or something to do with mutt.

**Comment by heywoodlh** [comment]
That would make sense. @BlitzKraft is there something you'd like me to do within the project itself to make it work better with Mutt? Or is this just a Mutt issue?

**Comment by BlitzKraft** [comment]
@heywoodlh I don't think there something to be fixed in urlscan, now that I've exhaustively searched. All I could hope for, is someone to reproduce this issue. Is there a method of invoking/running urlscan on text, that I didn't check for?

I am looking at mutt's source to hopefully find the bug.
